language: scala
jdk: openjdk8
scala:
   - 2.12.10 # scala version
   
branches:
  only:
    - master # build master branch only
script:
   - bash deploy.sh # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: public
